# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup Pages
      uses: actions/configure-pages@v5
      with:
          static_site_generator: next
    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
    - run: npm ci
    - run: npm run testCI
    - run: npm run build --if-present --prod 

    - name: Zip build files
      run: tar -cvzf build-artifact-${{ github.ref_name }}.tgz -C ./dist/wizard-score-board/browser/ .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GHA_LAUNCH_PAT }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GHA_LAUNCH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build-artifact-${{ github.ref_name }}.tgz
        asset_name: wsb-${{ github.ref_name }}.tgz
        asset_content_type: application/zip
    
    - name: Trigger deployement workflow
      env:
        GH_TOKEN: ${{ secrets.GHA_LAUNCH_PAT }}  
      run: |
        gh api -X POST /repos/coutcout/wizardScoreBoard/dispatches \
        -f "event_type=deploy" \
        -f "client_payload[tag]=${{ github.ref_name }}" 

  